name: Build LineageOS ROM

on:
  workflow_dispatch: # Allows you to manually trigger the build

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 10240
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc fontconfig schedtool python3

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize Repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1

    - name: Prepare Local Manifest (Device Sources)
      run: |
        cd workspace
        mkdir -p .repo/local_manifests
        cat <<EOF > .repo/local_manifests/benz.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <manifest>
            <project path="device/oneplus/benz" name="kdrag0nx/android_device_oneplus_benz" remote="github" revision="lineage-21" />

            <project path="kernel/oneplus/sm7550" name="OnePlus-Nord-CE4-development/android_kernel_oneplus_sm7550" remote="github" revision="lineage-21" />

            <project path="vendor/oneplus/benz" name="OnePlus-Nord-CE4-development/vendor_oneplus_benz" remote="github" revision="lineage-21" />

            <project path="hardware/oplus" name="LineageOS/android_hardware_oplus" remote="github" revision="lineage-21" />
        </manifest>
        EOF

    - name: Sync Repo
      run: |
        cd workspace
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build ROM
      run: |
        cd workspace
        source build/envsetup.sh
        lunch lineage_benz-userdebug
        mka bacon

    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: LineageOS-Benz
        path: workspace/out/target/product/benz/*.zip
